#include "chr_load.h"
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <ctype.h>

/* Generated by cmake/embed_file.cmake from data/chr.bmp */
extern const unsigned char chr_bmp_data[];
extern const unsigned int chr_bmp_len;

static uint8_t chr_data[16384];
static uint8_t blank_tile_idx = 0x24;
static uint16_t bg_bank_offset = 0;

static uint16_t read_le16(const uint8_t *data) {
    return (uint16_t)data[0] | ((uint16_t)data[1] << 8);
}

static uint32_t read_le32(const uint8_t *data) {
    return (uint32_t)data[0] | ((uint32_t)data[1] << 8) | ((uint32_t)data[2] << 16) | ((uint32_t)data[3] << 24);
}

static bool path_ext_equals(const char *path, const char *ext) {
    if (!path || !ext) return false;
    const char *dot = strrchr(path, '.');
    if (!dot) return false;
    dot++;
    while (*dot && *ext) {
        if (tolower((unsigned char)*dot) != tolower((unsigned char)*ext)) {
            return false;
        }
        dot++;
        ext++;
    }
    return *dot == '\0' && *ext == '\0';
}

static int load_chr_bin(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) return 0;

    memset(chr_data, 0, sizeof(chr_data));
    size_t read = fread(chr_data, 1, sizeof(chr_data), f);
    fclose(f);
    if (read >= 8192) {
        printf("Applying Battle City Layout: BG=Bank 1, SPR=Bank 0, 8x16 Sprites.\n");
        bg_bank_offset = 0x1000;
        blank_tile_idx = 0x24;
        printf("Loaded %zu bytes of CHR data. BG Offset: 0x%04X, Blank tile: 0x%02X\n", read, bg_bank_offset, blank_tile_idx);
        return 1;
    }
    return 0;
}

static uint8_t intensity_to_chrnibble(uint8_t g) {
    if (g < 64) return 0;
    if (g < 128) return 1;
    if (g < 192) return 2;
    return 3;
}

#define BMP_WIDTH   128
#define BMP_HEIGHT  256
#define BMP_OFFSET  (54 + 1024)
#define BMP_SIZE    (BMP_OFFSET + BMP_WIDTH * BMP_HEIGHT)

int load_chr_bmp_mem(const uint8_t *data, size_t size, const char *label) {
    if (size < BMP_SIZE) return 0;

    if (data[0] != 'B' || data[1] != 'M') return 0;
    if (read_le32(data + 10) != BMP_OFFSET) return 0;
    if (read_le32(data + 18) != BMP_WIDTH) return 0;
    if (read_le32(data + 22) != BMP_HEIGHT) return 0;
    if (read_le16(data + 28) != 8) return 0;
    if (read_le32(data + 30) != 0) return 0;

    const uint8_t *palette = data + 54;
    const uint8_t *pixels  = data + BMP_OFFSET;

    memset(chr_data, 0, sizeof(chr_data));

    for (size_t ty = 0; ty < BMP_HEIGHT / 8; ty++) {
        for (size_t tx = 0; tx < BMP_WIDTH / 8; tx++) {
            size_t tile_offset = (ty * (BMP_WIDTH / 8) + tx) * 16;

            for (size_t y = 0; y < 8; y++) {
                size_t src_y = BMP_HEIGHT - 1 - (ty * 8 + y);
                const uint8_t *src_row = &pixels[src_y * BMP_WIDTH + tx * 8];

                uint8_t p0 = 0, p1 = 0;

                for (size_t x = 0; x < 8; x++) {
                    uint8_t v = intensity_to_chrnibble(palette[src_row[x] * 4]);
                    p0 = (p0 << 1) | (v & 1);
                    p1 = (p1 << 1) | ((v >> 1) & 1);
                }

                chr_data[tile_offset + y]     = p0;
                chr_data[tile_offset + y + 8] = p1;
            }
        }
    }

    bg_bank_offset = 0x1000;
    blank_tile_idx = 0x24;

    printf("Loaded CHR from BMP image: %s. Tiles: %d, BG Offset: 0x%04X, Blank tile: 0x%02X\n",
           label, (BMP_WIDTH / 8) * (BMP_HEIGHT / 8), bg_bank_offset, blank_tile_idx);

    return 1;
}

int load_chr_bmp(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) return 0;

    uint8_t buf[BMP_SIZE];
    int ok = 0;

    if (fread(buf, 1, sizeof(buf), f) == sizeof(buf))
        ok = load_chr_bmp_mem(buf, sizeof(buf), path);

    fclose(f);
    return ok;
}

int load_chr(const char *path) {
    /* Try file-based loading first */
    if (path) {
        if (path_ext_equals(path, "bin")) {
            if (load_chr_bin(path)) return 1;
        }
        if (path_ext_equals(path, "bmp")) {
            if (load_chr_bmp(path)) return 1;
        }
        if (load_chr_bin(path)) return 1;
        if (load_chr_bmp(path)) return 1;
    }

    /* Fall back to embedded BMP */
    size_t embedded_size = (size_t)chr_bmp_len;
    if (load_chr_bmp_mem(chr_bmp_data, embedded_size, "embedded")) {
        return 1;
    }

    return 0;
}

uint16_t get_bg_bank_offset(void) {
    return bg_bank_offset;
}

uint8_t* gets_chr_ptr(void) {
    return chr_data;
}

uint8_t get_blank_tile_idx(void) {
    return blank_tile_idx;
}
